resources:
  repositories:

  - repository: MyGitHubRepo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: srkaranam
    name: srkaranam/Test
  - repository: MyGitHubRepo2 # The name used to reference this repository in the checkout step
    type: github
    endpoint: srkaranam
    name: srkaranam/Test2

    
trigger:
- master
schedules:
- cron: '0 18 * * *'
  displayName: Every night at 6pm
  

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: MyGitHubRepo1
- checkout: MyGitHubRepo2


- script: dir $(Build.SourcesDirectory)