resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test
  - repository: MyGitHubRepo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test1
    ref: master
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: MyGitHubRepo
- checkout: MyGitHubRepo1


- script: dir $(Build.SourcesDirectory)