# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more: 
# https://aka.ms/yaml


resources:
  repositories:
  - repository: Test
    type: github
    endpoint: "KIRTHISHKT"
    name: kirthishkt/srkarnam
  - repository: Test2
    type: github
    endpoint: "KIRTHISHKT"
    name: kirthishkt/srkaranam1
    
    

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  
steps:
- checkout: self
- checkout: Test
- checkout: Test2





- script: dir $(Build.SourcesDirectory)
