# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  repositories:
  - repository: Test
    type: github
    endpoint: srkaranam
    name: srkaranam/Test
  - repository: Test1
    type: github
    endpoint: srkaranam
    name: srkaranam/Test1
    
    


trigger:
- master

pool: default
  
steps:
- checkout: Test
#- checkout: Test1




- script: dir $(Build.SourcesDirectory)
