resources:
  repositories:

  - repository: MyGitHubRepo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: srkaranam
    name: srkaranam/Test
  - repository: MyGitHubRepo2 # The name used to reference this repository in the checkout step
    type: github
    endpoint: srkaranam
    name: srkaranam/Test

schedules:
 - cron: "36 15 */1 * *"
   displayName: Daily midnight build
   branches:
    include:
    - master
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: MyGitHubRepo1
- checkout: MyGitHubRepo2


- script: dir $(Build.SourcesDirectory)