# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  repositories:
  - repository: Test
    type: github
    endpoint: "GitHub - srkarana"
    name: srkaranam/Test
  - repository: Test2
    type: github
    endpoint: test
    name: srkarana/Test2
  - repository: Test3
    type: github
    endpoint: test
    name: srkarana/Test2
    
    

trigger:
- master

pool: Default
  
steps:
- checkout: self
- checkout: Test
- checkout: Test2
- checkout: Test3





- script: dir $(Build.SourcesDirectory)
