resources:
  repositories:

  - repository: MyGitHubRepo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test
schedules:
- cron: "0 0 21/1 * *"
  displayName: Daily midnight build
  
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: MyGitHubRepo1


- script: dir $(Build.SourcesDirectory)