resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkarana/Test
  

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: MyGitHubRepo


- script: dir $(Build.SourcesDirectory)