resources:
  repositories:
#  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
#    type: github
#    endpoint: test
#   name: srkaranam/Test
  - repository: MyGitHubRepo
    type: github
    endpoint: test
    name: srkaranam/Test1
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- checkout: MyGitHubRepo
- checkout: MyGitHubRepo


- script: dir $(Build.SourcesDirectory)